version: "3"

services:
  ui:
    image: swaggerapi/swagger-ui
    restart: always
    volumes:
      - ./docs:/usr/share/nginx/html
    environment:
      API_URL: ${SWAGGER_SPECIFICATION_URL:-/schema/openapi.app.yaml}
      ENVIRONMENT: ${ENVIRONMENT:-stg}
    tty: true
    ports:
      - ${SWAGGER_UI_PORT:-18080}:8080

  # swagger-api:
  #   image: stoplight/prism:3
  #   restart: always
  #   command: mock -h 0.0.0.0 /openapi.app.yaml
  #   volumes:
  #     - ./${ENVIRONMENT:-stg}/openapi.app.yaml:/openapi.app.yaml
  #   ports:
  #     - "${PRISM_PORT:-4010}:4010"
