version: "3"

services:
  ui:
    image: swaggerapi/swagger-ui
    restart: always
    volumes:
      - ./docs/dist/:/usr/share/nginx/html
      - ./docs/openapi.app.stg.yaml:/usr/share/nginx/html/openapi.app.stg.yaml
      - ./docs/openapi.admin.stg.yaml:/usr/share/nginx/html/openapi.admin.stg.yaml
      - ./docs/openapi.app.prod.yaml:/usr/share/nginx/html/openapi.app.prod.yaml
      - ./docs/openapi.admin.prod.yaml:/usr/share/nginx/html/openapi.admin.prod.yaml
    environment:
      API_URL: ../openapi.app.yaml
    ports:
      - ${SWAGGER_UI_PORT:-18080}:8080

  # swagger-api:
  #   image: stoplight/prism:3
  #   restart: always
  #   command: mock -h 0.0.0.0 /openapi.app.yaml
  #   volumes:
  #     - ./${ENVIRONMENT:-stg}/openapi.app.yaml:/openapi.app.yaml
  #   ports:
  #     - "${PRISM_PORT:-4010}:4010"
